### PR TITLE
Build with JDK 11 and 16

### PR DESCRIPTION
**Pull request by A248**
Depends on #8, otherwise building on JDK 16 will fail

### CODE REVIEW

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I tested this but for some reason it failed with JDK 16.

`Step 'google-java-format' found problem in 'src/main/java/org/tomlj/AccumulatingErrorListener.java':`

`java.lang.IllegalAccessError: class com.google.googlejavaformat.java.JavaInput (in unnamed module @0x2ff855c2) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x2ff855c2`

**Comment by A248** [comment]
That's odd; yesterday the build succeeded for me but today it failed with the same message, maybe due to gradle's caching. Regardless, I've fixed this issue now.

Partially as a consequence of JDK 16 compatibility, I've had to drop JDK 8 from the matrix. I do not see an issue with raising the build requirement to JDK 11 as long as we maintain runtime compatibility with JDK 8. The `release` compiler flag is the rock-solid way to do this: it will ensure we don't call JDK 9+ API methods, including by taking care of covariant return types.

Anyway, I was already planning to raise the build requirement to JDK 11 in a later PR focusing on adding a Java9 module descriptor. Might as well do it now.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
Do we really have to test this for JDK16 now?

I would also prefer not to add any workarounds and keep JDK8 compatibility.

**Comment by A248** [comment]
We can still have Java 8 compatibility, just with a JDK 11 *build-time* requirement. At runtime, compatibility with Java 8 is maintained.

Is there a specific reason you want to still build with JDK 8? Do you use Java 8 in your workspace?

This build-time requirement will actually allow us to remove workarounds, like errorprone's javac 9 requirement. I'm planning to PR another feature (Java 9 module support) which will also require Java 11 at build-time.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
> We can still have Java 8 compatibility, just with a JDK 11 build-time requirement. At runtime, compatibility with Java 8 is maintained.

Well then I don't see a problem with that.

> Is there a specific reason you want to still build with JDK 8? Do you use Java 8 in your workspace?

No, but I need Java 8 runtime compatibility, which shouldn't be a problem then.

**Pull request merged**
